checks:
    python:
        code_rating: true
        duplicate_code: true
        typecheck_maybe_no_member: true
        classes_valid_slots: true
        basic_missing_reversed_argument: true

build:
    environment:
        python: 3.4.1

    dependencies:
        before:
            - pip install -r requirements.txt
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
            environment:
                node:
                    version: 6.0.0
        tests: true

    tests:
        override:
            - command: 'coverage run -p --source=src src/setup.py build'
            - command: 'coverage run -p --source=src src/test_main.py'
            - command: 'coverage combine'
              coverage:
                    file: '.coverage'
                    config_file: '.coveragerc'
                    format: 'py-cc'
filter:
    excluded_paths:
        - '*/test/*'