# This is the build configuration for BMEcatconverter.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: python:3.4.7

pipelines:
  default:
    - step:
        caches:
          - pip
        script: # Modify the commands below to build your repository.
          - pip install -r requirements.txt
          - coverage run -p --source=src src/setup.py build
          - coverage run -p --source=src src/test_main.py 
          - coverage combine
          - coverage report
          - coverage xml
          - coverage html

  branches:
    master:
      - step:
          caches:
            - pip
          script: # Modify the commands below to build your repository.
            - pip install -r requirements.txt
            - coverage run -p --source=src src/setup.py build
            - coverage run -p --source=src src/test_main.py 
            - coverage combine
            - coverage report
            - coverage xml
            - coverage html
            # Upload Testcoverage 
            # - CODECLIMATE_REPO_TOKEN=7cab17cbed7019019ea4955c73a8099e2d8c1199833546e7b5e9223bbb1e6dc6 codeclimate-test-reporter