from test.datamodel.featureSetTest import FeatureSetTest
from test.datamodel.featureTest import FeatureTest
from test.datamodel.mimeTest import MimeTest
from test.datamodel.orderDetailsTest import OrderDetailsTest
from test.datamodel.priceDetailsTest import PriceDetailsTest
from test.datamodel.priceTest import PriceTest
from test.datamodel.productDetailsTest import ProductDetailsTest
from test.datamodel.productTest import ProductTest
from test.datamodel.referenceTest import ReferenceTest
from test.datamodel.treatmentClassTest import TreatmentClassTest
from test.datamodel.validatingObjectTest import ValidatingObjectTest
from test.datamodel.variantSetTest import VariantSetTest
from test.datamodel.variantTest import VariantTest
from test.datamodel.xmlObjectTest import XMLObjectTest
