from test.handler.xml.xmlImportTest import XMLImportTest
from test.handler.xml.xmlTransformationTest import XmlTransformationNonStrictValidationTest
from test.handler.xml.xmlTransformationsForStrictValidationTest import XmlTransformationForStrictValidationTest
